### ISSUE TITLE
Recenzja

### ISSUE THREAD

**Issue by Nowosad** [spacea/projekt-2021-timm#1]
Kwestie do poprawy:

- [x] Ogólny styl README można ulepszyć (np. używając pogrubień, itd. - https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet); W obecnej formie ten plik jest dość chaotyczny
- [x] W README powinny być zawarte wymagania (np. pakiety potrzebne do jego uruchomienia)
- [x] Czasami oprócz wyniku pojawiają się komunikaty ostrzeżeń (warning) - polecam je schować, żeby nie pojawiały się dla użytkowników
- [x] W podobnym kontekście zachęcam do stosowania programowania defensywnego - jak użytkownik poda złe parametry to powinien otrzymać odpowiedni error
- [x] Bez względu na wybraną datę, dostaję ten sam komunikat - ee_date('2021-03-20') Dane pochodzą z United States Geological Survey i obejmują czas od 2021-03-13 17:45:29 do 2021-04-12 17:15:35; trzeba to poprawić

**Comment by stef-ale** [comment]
W miarę naszych możliwości postarałyśmy się wprowadzić poprawki według Pana wskazówek. :)
